package sdk

var (
	requestTemplateResponse = `{  
		"type":"com.vmware.vcac.catalog.domain.request.CatalogItemProvisioningRequest",
		"catalogItemId":"feaedf73-560c-4612-a573-41667e017691",
		"requestedFor":"fritz@coke.sqa-horizon.local",
		"businessGroupId":"b2470b94-cbca-43db-be37-803cca7b0f1a",
		"description":null,
		"reasons":null,
		"data":{  
		   "_leaseDays":null,
		   "_number_of_instances":1,
		   "machine2.vsphere":{  
			  "componentTypeId":"com.vmware.csp.component.cafe.composition",
			  "componentId":null,
			  "classId":"Blueprint.Component.Declaration",
			  "typeFilter":"Prativa_CentOs*machine2.vsphere",
			  "data":{  
				 "_cluster":1,
				 "_hasChildren":false,
				 "cpu":1,
				 "datacenter_location":null,
				 "description":null,
				 "disks":[  
					{  
					   "componentTypeId":"com.vmware.csp.iaas.blueprint.service",
					   "componentId":null,
					   "classId":"Infrastructure.Compute.Machine.MachineDisk",
					   "typeFilter":null,
					   "data":{  
						  "capacity":8,
						  "custom_properties":null,
						  "id":1537301083687,
						  "initial_location":"",
						  "is_clone":true,
						  "label":"Hard disk 1",
						  "storage_reservation_policy":"",
						  "userCreated":false,
						  "volumeId":0
					   }
					}
				 ],
				 "display_location":false,
				 "guest_customization_specification":null,
				 "location.loc":"",
				 "machine_prefix":null,
				 "max_network_adapters":-1,
				 "max_per_user":0,
				 "max_volumes":60,
				 "memory":1024,
				 "nics":null,
				 "os_arch":"x86_64",
				 "os_distribution":null,
				 "os_type":"Linux",
				 "os_version":null,
				 "ovfAuthNeeded":false,
				 "ovf_proxy_endpoint":null,
				 "ovf_url":null,
				 "ovf_url_pwd":null,
				 "ovf_url_username":null,
				 "ovf_use_proxy":false,
				 "property_groups":null,
				 "reservation_policy":null,
				 "security_groups":[  
	 
				 ],
				 "security_tags":[  
	 
				 ],
				 "snapshot_name":null,
				 "source_machine_external_snapshot":null,
				 "source_machine_vmsnapshot":null,
				 "storage":8
			  }
		   }
		}
	 }`

	requestTemplateErrorResponse = `{  
		"errors":[  
		   {  
			  "code":20116,
			  "source":null,
			  "message":"Unable to find the specified catalog item in the service catalog: feaedf73-560c-4612-a573-0041667e0176.",
			  "systemMessage":"Unable to find the specified catalog item in the service catalog: feaedf73-560c-4612-a573-0041667e0176.",
			  "moreInfoUrl":null
		   }
		]
	 }`

	catalogItemResp = `{  
		"catalogItem":{  
		   "callbacks":null,
		   "catalogItemTypeRef":{  
			  "id":"com.vmware.csp.component.cafe.composition.blueprint",
			  "label":"Composite Blueprint"
		   },
		   "dateCreated":"2015-12-22T03:16:19.289Z",
		   "description":"CentOS 6.3 IaaS Blueprint",
		   "forms":{  
			  "itemDetails":{  
				 "type":"external",
				 "formId":"composition.catalog.item.details"
			  },
			  "catalogRequestInfoHidden":true,
			  "requestFormScale":"BIG",
			  "requestSubmission":{  
				 "type":"extension",
				 "extensionId":"com.vmware.vcac.core.design.blueprints.requestForm",
				 "extensionPointId":null
			  },
			  "requestDetails":{  
				 "type":"extension",
				 "extensionId":"com.vmware.vcac.core.design.blueprints.requestDetailsForm",
				 "extensionPointId":null
			  },
			  "requestPreApproval":null,
			  "requestPostApproval":null
		   },
		   "iconId":"e5dd4fba-45ed-4943-b1fc-7f96239286be",
		   "id":"e5dd4fba-45ed-4943-b1fc-7f96239286be",
		   "isNoteworthy":false,
		   "lastUpdatedDate":"2017-01-06T05:12:56.690Z",
		   "name":"CentOS 6.3",
		   "organization":{  
			  "tenantRef":"vsphere.local",
			  "tenantLabel":"vsphere.local",
			  "subtenantRef":null,
			  "subtenantLabel":null
		   },
		   "outputResourceTypeRef":{  
			  "id":"composition.resource.type.deployment",
			  "label":"Deployment"
		   },
		   "providerBinding":{  
			  "bindingId":"vsphere.local!::!CentOS63",
			  "providerRef":{  
				 "id":"2fbaabc5-3a48-488a-9f2a-a42616345445",
				 "label":"Blueprint Service"
			  }
		   },
		   "serviceRef":{  
			  "id":"baad0ad2-8b96-4347-b188-f534dad53a0d",
			  "label":"Infrastructure"
		   },
		   "status":"PUBLISHED",
		   "statusName":"Published",
		   "quota":0,
		   "version":4,
		   "requestable":true
		},
		"entitledOrganizations":[  
		   {  
			  "tenantRef":"vsphere.local",
			  "tenantLabel":"vsphere.local",
			  "subtenantRef":"53619006-56bb-4788-9723-9eab79752cc1",
			  "subtenantLabel":"Content"
		   }
		]
	 }`

	entitledCatalogItemViewsResponse = `{  
		"links":[  
	 
		],
		"content":[  
		   {  
			  "@type":"ConsumerEntitledCatalogItemView",
			  "entitledOrganizations":[  
				 {  
					"tenantRef":"qe",
					"tenantLabel":"QETenant",
					"subtenantRef":"b2470b94-cbca-43db-be37-803cca7b0f1a",
					"subtenantLabel":"Development"
				 }
			  ],
			  "catalogItemId":"2e13fd45-a85e-4985-b89e-4ebb19ab272c",
			  "name":"NoSoftwareMachine",
			  "description":null,
			  "isNoteworthy":false,
			  "dateCreated":"2018-08-31T19:30:51.036Z",
			  "lastUpdatedDate":"2018-09-18T19:37:50.903Z",
			  "links":[  
				 {  
					"@type":"link",
					"rel":"GET: Request Template",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/2e13fd45-a85e-4985-b89e-4ebb19ab272c/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: Submit Request",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/2e13fd45-a85e-4985-b89e-4ebb19ab272c/requests"
				 }
			  ],
			  "iconId":"composition.blueprint.png",
			  "catalogItemTypeRef":{  
				 "id":"com.vmware.csp.component.cafe.composition.blueprint",
				 "label":"Composite Blueprint"
			  },
			  "serviceRef":{  
				 "id":"d33afbc2-954d-416d-8d4a-bc4ad1b66058",
				 "label":"test-service"
			  },
			  "outputResourceTypeRef":{  
				 "id":"composition.resource.type.deployment",
				 "label":"Deployment"
			  }
		   },
		   {  
			  "@type":"ConsumerEntitledCatalogItemView",
			  "entitledOrganizations":[  
				 {  
					"tenantRef":"qe",
					"tenantLabel":"QETenant",
					"subtenantRef":"b2470b94-cbca-43db-be37-803cca7b0f1a",
					"subtenantLabel":"Development"
				 }
			  ],
			  "catalogItemId":"b7472041-d49b-44f2-a9b6-8ea714f55c55",
			  "name":"Dukes Bank Application",
			  "description":"Three-tier Dukes Bank application on Linux nodes; Apache HTTP Server for load balancer, JBoss Server for application server, and MySQL Server for database server. This is the basic version of Dukes Bank on Linux nodes.",
			  "isNoteworthy":false,
			  "dateCreated":"2018-08-31T18:12:49.680Z",
			  "lastUpdatedDate":"2018-09-18T19:24:09.673Z",
			  "links":[  
				 {  
					"@type":"link",
					"rel":"GET: Request Template",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/b7472041-d49b-44f2-a9b6-8ea714f55c55/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: Submit Request",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/b7472041-d49b-44f2-a9b6-8ea714f55c55/requests"
				 }
			  ],
			  "iconId":"composition.blueprint.png",
			  "catalogItemTypeRef":{  
				 "id":"com.vmware.csp.component.cafe.composition.blueprint",
				 "label":"Composite Blueprint"
			  },
			  "serviceRef":{  
				 "id":"d33afbc2-954d-416d-8d4a-bc4ad1b66058",
				 "label":"test-service"
			  },
			  "outputResourceTypeRef":{  
				 "id":"composition.resource.type.deployment",
				 "label":"Deployment"
			  }
		   },
		   {  
			  "@type":"ConsumerEntitledCatalogItemView",
			  "entitledOrganizations":[  
				 {  
					"tenantRef":"qe",
					"tenantLabel":"QETenant",
					"subtenantRef":"b2470b94-cbca-43db-be37-803cca7b0f1a",
					"subtenantLabel":"Development"
				 }
			  ],
			  "catalogItemId":"1eb8e1d4-152e-4a93-a3b6-265df6870555",
			  "name":"Azure Machine (2)",
			  "description":"Creates new Azure virtual machine",
			  "isNoteworthy":false,
			  "dateCreated":"2018-09-18T19:40:19.172Z",
			  "lastUpdatedDate":"2018-09-18T19:41:39.432Z",
			  "links":[  
				 {  
					"@type":"link",
					"rel":"GET: Request Template",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/1eb8e1d4-152e-4a93-a3b6-265df6870555/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: Submit Request",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/1eb8e1d4-152e-4a93-a3b6-265df6870555/requests"
				 }
			  ],
			  "iconId":"_internal!::!dda3cc3f-f2da-45f5-bc64-a292c1ace3ba_icon",
			  "catalogItemTypeRef":{  
				 "id":"com.vmware.csp.core.designer.service.serviceblueprint",
				 "label":"XaaS Blueprint"
			  },
			  "serviceRef":{  
				 "id":"d33afbc2-954d-416d-8d4a-bc4ad1b66058",
				 "label":"test-service"
			  },
			  "outputResourceTypeRef":{  
				 "id":"_internal!::!dda3cc3f-f2da-45f5-bc64-a292c1ace3ba",
				 "label":"Azure Virtual Machine"
			  }
		   },
		   {  
			  "@type":"ConsumerEntitledCatalogItemView",
			  "entitledOrganizations":[  
				 {  
					"tenantRef":"qe",
					"tenantLabel":"QETenant",
					"subtenantRef":"b2470b94-cbca-43db-be37-803cca7b0f1a",
					"subtenantLabel":"Development"
				 }
			  ],
			  "catalogItemId":"feaedf73-560c-4612-a573-41667e017691",
			  "name":"CentOs",
			  "description":"",
			  "isNoteworthy":false,
			  "dateCreated":"2018-09-18T20:04:55.805Z",
			  "lastUpdatedDate":"2018-09-27T22:52:48.390Z",
			  "links":[  
				 {  
					"@type":"link",
					"rel":"GET: Request Template",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/feaedf73-560c-4612-a573-41667e017691/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: Submit Request",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItems/feaedf73-560c-4612-a573-41667e017691/requests"
				 }
			  ],
			  "iconId":"composition.blueprint.png",
			  "catalogItemTypeRef":{  
				 "id":"com.vmware.csp.component.cafe.composition.blueprint",
				 "label":"Composite Blueprint"
			  },
			  "serviceRef":{  
				 "id":"d33afbc2-954d-416d-8d4a-bc4ad1b66058",
				 "label":"test-service"
			  },
			  "outputResourceTypeRef":{  
				 "id":"composition.resource.type.deployment",
				 "label":"Deployment"
			  }
		   }
		],
		"metadata":{  
		   "size":20,
		   "totalElements":4,
		   "totalPages":1,
		   "number":1,
		   "offset":0
		}
	 }`

	subTenantsResponse = `{  
		"links":[  
	 
		],
		"content":[  
		   {  
			  "@type":"Subtenant",
			  "id":"b2470b94-cbca-43db-be37-803cca7b0f1a",
			  "name":"Development",
			  "description":"created by demo content",
			  "subtenantRoles":null,
			  "tenant":"qe",
			  "extensionData":{  
				 "entries":[  
					{  
					   "key":"iaas-manager-emails",
					   "value":{  
						  "type":"string",
						  "value":"astoyanov@vcac.sqa-horizon.local"
					   }
					}
				 ]
			  }
		   },
		   {  
			  "@type":"Subtenant",
			  "id":"ff371ec6-d4d8-4dee-aa73-f09e1bb3a4fd",
			  "name":"Quality Engineering",
			  "description":"created by demo content",
			  "subtenantRoles":null,
			  "tenant":"qe",
			  "extensionData":{  
				 "entries":[  
					{  
					   "key":"iaas-manager-emails",
					   "value":{  
						  "type":"string",
						  "value":"astoyanov@vcac.sqa-horizon.local"
					   }
					}
				 ]
			  }
		   },
		   {  
			  "@type":"Subtenant",
			  "id":"e11a782e-cff3-4707-b1e1-88940507dab3",
			  "name":"Finance",
			  "description":"created by demo content",
			  "subtenantRoles":null,
			  "tenant":"qe",
			  "extensionData":{  
				 "entries":[  
					{  
					   "key":"iaas-manager-emails",
					   "value":{  
						  "type":"string",
						  "value":"gloria@coke.sqa-horizon.local"
					   }
					}
				 ]
			  }
		   },
		   {  
			  "@type":"Subtenant",
			  "id":"6273f684-210c-4839-85ec-573346f53799",
			  "name":"cloudclient-ITs-bg",
			  "description":"",
			  "subtenantRoles":null,
			  "tenant":"qe",
			  "extensionData":{  
				 "entries":[  
					{  
					   "key":"iaas-machine-prefix",
					   "value":{  
						  "type":"string",
						  "value":"b272b729-1583-4e6e-b299-15c293a6d0fa"
					   }
					},
					{  
					   "key":"iaas-ad-container",
					   "value":{  
						  "type":"string",
						  "value":""
					   }
					},
					{  
					   "key":"iaas-manager-emails",
					   "value":{  
						  "type":"string",
						  "value":"fritz@sqa-local.com"
					   }
					}
				 ]
			  }
		   }
		],
		"metadata":{  
		   "size":20,
		   "totalElements":4,
		   "totalPages":1,
		   "number":1,
		   "offset":0
		}
	 }`

	requestStatusResponse = `{  
		"@type":"CatalogItemRequest",
		"id":"adca9535-4a35-4981-8864-28643bd990b0",
		"iconId":"composition.blueprint.png",
		"version":3,
		"requestNumber":424,
		"state":"IN_PROGRESS",
		"description":"Prativa's deployment 1",
		"reasons":"Testing the vRA 7 Terraform plugin",
		"requestedFor":"fritz@coke.sqa-horizon.local",
		"requestedBy":"fritz@coke.sqa-horizon.local",
		"organization":{  
		   "tenantRef":"qe",
		   "tenantLabel":"QETenant",
		   "subtenantRef":"b2470b94-cbca-43db-be37-803cca7b0f1a",
		   "subtenantLabel":"Development"
		},
		"requestorEntitlementId":"93f0fc4b-de67-4a03-a32e-f689ce016ca4",
		"preApprovalId":null,
		"postApprovalId":null,
		"dateCreated":"2019-02-26T23:44:43.223Z",
		"lastUpdated":"2019-02-26T23:44:45.142Z",
		"dateSubmitted":"2019-02-26T23:44:43.223Z",
		"dateApproved":null,
		"dateCompleted":null,
		"quote":{  
		   "leasePeriod":{  
			  "type":"timeSpan",
			  "unit":"DAYS",
			  "amount":5
		   },
		   "leaseRate":null,
		   "totalLeaseCost":null
		},
		"requestCompletion":null,
		"requestData":{  
		   "entries":[  
			  {  
				 "key":"provider-_leaseDays",
				 "value":{  
					"type":"integer",
					"value":5
				 }
			  },
			  {  
				 "key":"provider-machine2.vsphere",
				 "value":{  
					"type":"complex",
					"componentTypeId":"com.vmware.csp.component.cafe.composition",
					"componentId":null,
					"classId":"Blueprint.Component.Declaration",
					"typeFilter":"Prativa_CentOs*machine2.vsphere",
					"values":{  
					   "entries":[  
						  {  
							 "key":"snapshot_name",
							 "value":null
						  },
						  {  
							 "key":"memory",
							 "value":{  
								"type":"integer",
								"value":1024
							 }
						  },
						  {  
							 "key":"disks",
							 "value":{  
								"type":"multiple",
								"elementTypeId":"COMPLEX",
								"items":[  
								   {  
									  "type":"complex",
									  "componentTypeId":"com.vmware.csp.iaas.blueprint.service",
									  "componentId":null,
									  "classId":"Infrastructure.Compute.Machine.MachineDisk",
									  "typeFilter":null,
									  "values":{  
										 "entries":[  
											{  
											   "key":"is_clone",
											   "value":{  
												  "type":"boolean",
												  "value":true
											   }
											},
											{  
											   "key":"initial_location",
											   "value":{  
												  "type":"string",
												  "value":""
											   }
											},
											{  
											   "key":"volumeId",
											   "value":{  
												  "type":"string",
												  "value":"0"
											   }
											},
											{  
											   "key":"custom_properties",
											   "value":null
											},
											{  
											   "key":"id",
											   "value":{  
												  "type":"integer",
												  "value":1537301083687
											   }
											},
											{  
											   "key":"label",
											   "value":{  
												  "type":"string",
												  "value":"Hard disk 1"
											   }
											},
											{  
											   "key":"userCreated",
											   "value":{  
												  "type":"boolean",
												  "value":false
											   }
											},
											{  
											   "key":"storage_reservation_policy",
											   "value":{  
												  "type":"string",
												  "value":""
											   }
											},
											{  
											   "key":"capacity",
											   "value":{  
												  "type":"integer",
												  "value":8
											   }
											}
										 ]
									  }
								   }
								]
							 }
						  },
						  {  
							 "key":"ovf_use_proxy",
							 "value":{  
								"type":"boolean",
								"value":false
							 }
						  },
						  {  
							 "key":"description",
							 "value":null
						  },
						  {  
							 "key":"storage",
							 "value":{  
								"type":"integer",
								"value":8
							 }
						  },
						  {  
							 "key":"guest_customization_specification",
							 "value":null
						  },
						  {  
							 "key":"_hasChildren",
							 "value":{  
								"type":"boolean",
								"value":false
							 }
						  },
						  {  
							 "key":"os_distribution",
							 "value":null
						  },
						  {  
							 "key":"reservation_policy",
							 "value":null
						  },
						  {  
							 "key":"max_network_adapters",
							 "value":{  
								"type":"integer",
								"value":-1
							 }
						  },
						  {  
							 "key":"machine_prefix",
							 "value":null
						  },
						  {  
							 "key":"max_per_user",
							 "value":{  
								"type":"integer",
								"value":0
							 }
						  },
						  {  
							 "key":"nics",
							 "value":null
						  },
						  {  
							 "key":"ovfAuthNeeded",
							 "value":{  
								"type":"boolean",
								"value":false
							 }
						  },
						  {  
							 "key":"source_machine_vmsnapshot",
							 "value":null
						  },
						  {  
							 "key":"display_location",
							 "value":{  
								"type":"boolean",
								"value":false
							 }
						  },
						  {  
							 "key":"os_version",
							 "value":null
						  },
						  {  
							 "key":"os_arch",
							 "value":{  
								"type":"string",
								"value":"x86_64"
							 }
						  },
						  {  
							 "key":"cpu",
							 "value":{  
								"type":"integer",
								"value":1
							 }
						  },
						  {  
							 "key":"datacenter_location",
							 "value":null
						  },
						  {  
							 "key":"property_groups",
							 "value":null
						  },
						  {  
							 "key":"ovf_proxy_endpoint",
							 "value":null
						  },
						  {  
							 "key":"_cluster",
							 "value":{  
								"type":"integer",
								"value":1
							 }
						  },
						  {  
							 "key":"security_groups",
							 "value":{  
								"type":"multiple",
								"elementTypeId":"ENTITY_REFERENCE",
								"items":[  
	 
								]
							 }
						  },
						  {  
							 "key":"location.loc",
							 "value":{  
								"type":"string",
								"value":"Palo Alto 1"
							 }
						  },
						  {  
							 "key":"ovf_url_username",
							 "value":null
						  },
						  {  
							 "key":"ovf_url",
							 "value":null
						  },
						  {  
							 "key":"max_volumes",
							 "value":{  
								"type":"integer",
								"value":60
							 }
						  },
						  {  
							 "key":"os_type",
							 "value":{  
								"type":"string",
								"value":"Linux"
							 }
						  },
						  {  
							 "key":"ovf_url_pwd",
							 "value":null
						  },
						  {  
							 "key":"source_machine_external_snapshot",
							 "value":null
						  },
						  {  
							 "key":"security_tags",
							 "value":{  
								"type":"multiple",
								"elementTypeId":"ENTITY_REFERENCE",
								"items":[  
	 
								]
							 }
						  }
					   ]
					}
				 }
			  },
			  {  
				 "key":"provider-providerId",
				 "value":{  
					"type":"string",
					"value":"701feaf9-c31c-4bf1-86b6-8638002e32eb"
				 }
			  },
			  {  
				 "key":"provider-providerBindingId",
				 "value":{  
					"type":"string",
					"value":"Prativa_CentOs"
				 }
			  },
			  {  
				 "key":"provider-_number_of_instances",
				 "value":{  
					"type":"integer",
					"value":1
				 }
			  },
			  {  
				 "key":"provider-subtenantId",
				 "value":{  
					"type":"string",
					"value":"b2470b94-cbca-43db-be37-803cca7b0f1a"
				 }
			  }
		   ]
		},
		"retriesRemaining":3,
		"requestedItemName":"Prativa_CentOs",
		"requestedItemDescription":"",
		"components":null,
		"successful":false,
		"final":false,
		"stateName":"In Progress",
		"catalogItemRef":{  
		   "id":"feaedf73-560c-4612-a573-41667e017691",
		   "label":"Prativa_CentOs"
		},
		"catalogItemProviderBinding":{  
		   "bindingId":"qe!::!Prativa_CentOs",
		   "providerRef":{  
			  "id":"701feaf9-c31c-4bf1-86b6-8638002e32eb",
			  "label":"Blueprint Service"
		   }
		},
		"phase":"IN_PROGRESS",
		"executionStatus":"STARTED",
		"waitingStatus":"WAITING_FOR_PROVIDER",
		"approvalStatus":"PRE_APPROVED"
	 }`

	requestStatusErrResponse = `{  
		"errors":[  
		   {  
			  "code":20111,
			  "source":null,
			  "message":"Unable to find the specified request in the service catalog: adca9535-4a35-4981-8864-00000028643b.",
			  "systemMessage":"Unable to find the specified request in the service catalog: adca9535-4a35-4981-8864-00000028643b.",
			  "moreInfoUrl":null
		   }
		]
	 }`

	deploymentStateResponse = `{  
		"links":[  
	 
		],
		"content":[  
		   {  
			  "@type":"CatalogResourceView",
			  "resourceId":"1ffcd9fe-d96e-47ce-9509-cdbae24862e3",
			  "iconId":"composition.blueprint.png",
			  "name":"Prativa_CentOs-86390713",
			  "description":"Prativa's deployment 1",
			  "status":null,
			  "catalogItemId":"feaedf73-560c-4612-a573-41667e017691",
			  "catalogItemLabel":"Prativa_CentOs",
			  "requestId":"594bf7ec-c8d2-4a0d-8477-553ed987aa48",
			  "requestState":"SUCCESSFUL",
			  "resourceType":"composition.resource.type.deployment",
			  "owners":[  
				 "Fritz Arbeiter"
			  ],
			  "businessGroupId":"b2470b94-cbca-43db-be37-803cca7b0f1a",
			  "tenantId":"qe",
			  "dateCreated":"2019-02-27T00:11:00.526Z",
			  "lastUpdated":"2019-02-27T00:26:12.369Z",
			  "lease":{  
				 "start":"2019-02-27T00:11:12.040Z",
				 "end":"2019-03-04T00:11:12.040Z"
			  },
			  "costs":null,
			  "costToDate":null,
			  "totalCost":null,
			  "parentResourceId":null,
			  "hasChildren":true,
			  "data":{  
				 "isResumable":false
			  },
			  "links":[  
				 {  
					"@type":"link",
					"rel":"GET: Catalog Item",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/entitledCatalogItemViews/feaedf73-560c-4612-a573-41667e017691"
				 },
				 {  
					"@type":"link",
					"rel":"GET: Request",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/requests/594bf7ec-c8d2-4a0d-8477-553ed987aa48"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.cafe.composition@resource.action.deployment.changelease.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/e737406a-3d14-4207-8ee4-92bdae60d5b5/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.cafe.composition@resource.action.deployment.changelease.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/e737406a-3d14-4207-8ee4-92bdae60d5b5/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.cafe.composition@resource.action.deployment.changeowner.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/d981a60e-42cf-42d8-8b3d-4e259da47edf/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.cafe.composition@resource.action.deployment.changeowner.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/d981a60e-42cf-42d8-8b3d-4e259da47edf/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.network.service@resource.action.changesecurity.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/0974c82d-9f87-43a1-bdc8-84bf561e620d/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.network.service@resource.action.changesecurity.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/0974c82d-9f87-43a1-bdc8-84bf561e620d/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.cafe.composition@resource.action.deployment.destroy.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/356d45a1-d30e-4def-86c9-10cb9aa2b0de/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.cafe.composition@resource.action.deployment.destroy.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/356d45a1-d30e-4def-86c9-10cb9aa2b0de/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.cafe.composition@resource.action.deployment.archive.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/7cc9b9fa-8040-47f4-8222-d103602002ef/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.cafe.composition@resource.action.deployment.archive.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/7cc9b9fa-8040-47f4-8222-d103602002ef/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.cafe.composition@resource.action.deployment.scalein.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/45dd0bff-7b8b-4411-9576-640f4f9b7871/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.cafe.composition@resource.action.deployment.scalein.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/45dd0bff-7b8b-4411-9576-640f4f9b7871/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.cafe.composition@resource.action.deployment.scaleout.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/7d66f361-ce64-493a-be4f-fc042b6908f5/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.cafe.composition@resource.action.deployment.scaleout.name}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/1ffcd9fe-d96e-47ce-9509-cdbae24862e3/actions/7d66f361-ce64-493a-be4f-fc042b6908f5/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET: Child Resources",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resourceViews?managedOnly=false&withExtendedData=true&withOperations=true&%24filter=parentResource%20eq%20%271ffcd9fe-d96e-47ce-9509-cdbae24862e3%27"
				 }
			  ]
		   },
		   {  
			  "@type":"CatalogResourceView",
			  "resourceId":"4a7a33a8-6b21-461c-a618-442044059ef8",
			  "iconId":"Infrastructure.CatalogItem.Machine.Virtual.vSphere",
			  "name":"Development0231",
			  "description":null,
			  "status":"UnprovisionMachine",
			  "catalogItemId":null,
			  "catalogItemLabel":null,
			  "requestId":"594bf7ec-c8d2-4a0d-8477-553ed987aa48",
			  "requestState":"SUCCESSFUL",
			  "resourceType":"Infrastructure.Virtual",
			  "owners":[  
				 "Fritz Arbeiter"
			  ],
			  "businessGroupId":"b2470b94-cbca-43db-be37-803cca7b0f1a",
			  "tenantId":"qe",
			  "dateCreated":"2019-02-27T00:14:53.390Z",
			  "lastUpdated":"2019-02-27T00:26:07.998Z",
			  "lease":{  
				 "start":"2019-02-27T00:11:12.040Z",
				 "end":"2019-03-04T00:11:12.040Z"
			  },
			  "costs":null,
			  "costToDate":null,
			  "totalCost":null,
			  "parentResourceId":"1ffcd9fe-d96e-47ce-9509-cdbae24862e3",
			  "hasChildren":false,
			  "data":{  
				 "Component":"machine2.vsphere",
				 "DISK_VOLUMES":[  
					{  
					   "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
					   "componentId":null,
					   "classId":"dynamicops.api.model.DiskInputModel",
					   "typeFilter":null,
					   "data":{  
						  "DISK_CAPACITY":8,
						  "DISK_INPUT_ID":"DISK_INPUT_ID1",
						  "DISK_LABEL":"Hard disk 1"
					   }
					}
				 ],
				 "Destroy":true,
				 "EXTERNAL_REFERENCE_ID":"vm-12086",
				 "IS_COMPONENT_MACHINE":false,
				 "MachineBlueprintName":"Prativa_CentOs",
				 "MachineCPU":2,
				 "MachineDailyCost":0.0,
				 "MachineDestructionDate":"2019-03-04T00:11:15.377Z",
				 "MachineExpirationDate":"2019-03-04T00:11:15.377Z",
				 "MachineGroupName":"Development",
				 "MachineGuestOperatingSystem":null,
				 "MachineInterfaceDisplayName":"vSphere (vCenter)",
				 "MachineInterfaceType":"vSphere",
				 "MachineMemory":1024,
				 "MachineName":"Development0231",
				 "MachineReservationName":"reservation-tf",
				 "MachineStorage":8,
				 "MachineType":"Virtual",
				 "NETWORK_LIST":[  
					{  
					   "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
					   "componentId":null,
					   "classId":"dynamicops.api.model.NetworkViewModel",
					   "typeFilter":null,
					   "data":{  
						  "NETWORK_MAC_ADDRESS":"00:50:56:b6:78:c6",
						  "NETWORK_NAME":"dvPortGroup-wdc-sdm-vm-1521"
					   }
					}
				 ],
				 "SNAPSHOT_LIST":[  
	 
				 ],
				 "Unregister":true,
				 "VirtualMachine.Admin.UUID":"50361e44-a247-eae6-1117-3132560d0746",
				 "endpointExternalReferenceId":"827cddd6-9fd7-4477-bd2f-89b6b6d04337",
				 "ip_address":"10.145.155.50",
				 "machineId":"8432ad3c-7267-43e0-9a15-e7fe52cd6fc9"
			  },
			  "links":[  
				 {  
					"@type":"link",
					"rel":"GET: Request",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/requests/594bf7ec-c8d2-4a0d-8477-553ed987aa48"
				 },
				 {  
					"@type":"link",
					"rel":"GET: Parent Resource",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resourceViews/1ffcd9fe-d96e-47ce-9509-cdbae24862e3"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name.virtual.Destroy}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/4a7a33a8-6b21-461c-a618-442044059ef8/actions/95e60c87-e4d6-4458-9bfe-af7955cadc06/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name.virtual.Destroy}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/4a7a33a8-6b21-461c-a618-442044059ef8/actions/95e60c87-e4d6-4458-9bfe-af7955cadc06/requests"
				 },
				 {  
					"@type":"link",
					"rel":"GET Template: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name.machine.Unregister}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/4a7a33a8-6b21-461c-a618-442044059ef8/actions/28ef23c1-dc33-4f95-87fb-c25fa11b304a/requests/template"
				 },
				 {  
					"@type":"link",
					"rel":"POST: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name.machine.Unregister}",
					"href":"https://cava-n-80-072.eng.vmware.com/catalog-service/api/consumer/resources/4a7a33a8-6b21-461c-a618-442044059ef8/actions/28ef23c1-dc33-4f95-87fb-c25fa11b304a/requests"
				 }
			  ]
		   }
		],
		"metadata":{  
		   "size":20,
		   "totalElements":2,
		   "totalPages":1,
		   "number":1,
		   "offset":0
		}
	 }`

	resourceActionsResponse = `{  
		"links":[  
	 
		],
		"content":[  
		   {  
			  "@type":"CatalogResource",
			  "id":"69ddca78-7ed7-45e2-9f05-a4a4c8803e5c",
			  "iconId":"composition.blueprint.png",
			  "resourceTypeRef":{  
				 "id":"composition.resource.type.deployment",
				 "label":"Deployment"
			  },
			  "name":"Prativa_CentOs-66559687",
			  "description":"Prativa's deployment 1",
			  "status":"ACTIVE",
			  "catalogItem":{  
				 "id":"feaedf73-560c-4612-a573-41667e017691",
				 "label":"Prativa_CentOs"
			  },
			  "requestId":"6ec160e5-41c5-4b1d-8ddc-e89c426957c6",
			  "requestState":"SUCCESSFUL",
			  "providerBinding":{  
				 "bindingId":"74c9eeba-8c42-4150-a39e-8785f597813a",
				 "providerRef":{  
					"id":"701feaf9-c31c-4bf1-86b6-8638002e32eb",
					"label":"Blueprint Service"
				 }
			  },
			  "owners":[  
				 {  
					"tenantName":"qe",
					"ref":"fritz@coke.sqa-horizon.local",
					"type":"USER",
					"value":"Fritz Arbeiter"
				 }
			  ],
			  "organization":{  
				 "tenantRef":"qe",
				 "tenantLabel":"QETenant",
				 "subtenantRef":"b2470b94-cbca-43db-be37-803cca7b0f1a",
				 "subtenantLabel":"Development"
			  },
			  "dateCreated":"2019-02-27T00:59:23.520Z",
			  "lastUpdated":"2019-02-27T01:11:58.959Z",
			  "hasLease":true,
			  "lease":{  
				 "start":"2019-02-27T00:59:28.210Z",
				 "end":"2019-03-04T00:59:28.210Z"
			  },
			  "leaseForDisplay":{  
				 "type":"timeSpan",
				 "unit":"DAYS",
				 "amount":5
			  },
			  "hasCosts":true,
			  "costs":null,
			  "costToDate":null,
			  "totalCost":null,
			  "expenseMonthToDate":{  
				 "amount":null,
				 "currencyCode":null,
				 "asOnDate":null
			  },
			  "parentResourceRef":null,
			  "hasChildren":true,
			  "operations":[  
				 {  
					"name":"Change Lease",
					"description":"Change lease of a deployment and all its component resources.",
					"iconId":"composition.changelease.png",
					"type":"ACTION",
					"id":"e737406a-3d14-4207-8ee4-92bdae60d5b5",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.component.cafe.composition",
					"bindingId":"composition.resource.action.deployment.changelease",
					"hasForm":true,
					"formScale":"SMALL"
				 },
				 {  
					"name":"Change Owner",
					"description":"Change owner of a deployment and all its component resources.",
					"iconId":"composition.changeowner.png",
					"type":"ACTION",
					"id":"d981a60e-42cf-42d8-8b3d-4e259da47edf",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.component.cafe.composition",
					"bindingId":"composition.resource.action.deployment.changeowner",
					"hasForm":true,
					"formScale":"SMALL"
				 },
				 {  
					"name":"Change Security",
					"description":"Add or remove security objects for virtual machines in this deployment.",
					"iconId":"icon_changesecurity",
					"type":"ACTION",
					"id":"0974c82d-9f87-43a1-bdc8-84bf561e620d",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.component.network.service",
					"bindingId":"composition.resource.type.deployment.Action.ChangeSecurity",
					"hasForm":true,
					"formScale":"BIG"
				 },
				 {  
					"name":"Destroy",
					"description":"Destroys a deployment and all constituent resources.",
					"iconId":"composition.destroy.png",
					"type":"ACTION",
					"id":"356d45a1-d30e-4def-86c9-10cb9aa2b0de",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.component.cafe.composition",
					"bindingId":"composition.resource.action.deployment.destroy",
					"hasForm":true,
					"formScale":"BIG"
				 },
				 {  
					"name":"Expire",
					"description":"Expires a deployment and all constituent resources.",
					"iconId":"composition.archive.png",
					"type":"ACTION",
					"id":"7cc9b9fa-8040-47f4-8222-d103602002ef",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.component.cafe.composition",
					"bindingId":"composition.resource.action.deployment.archive",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Scale In",
					"description":"Scales in any scalable component in a deployment.",
					"iconId":"composition.scalein.png",
					"type":"ACTION",
					"id":"45dd0bff-7b8b-4411-9576-640f4f9b7871",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.component.cafe.composition",
					"bindingId":"composition.resource.action.deployment.scalein",
					"hasForm":true,
					"formScale":"BIG"
				 },
				 {  
					"name":"Scale Out",
					"description":"Scales out any scalable component in a deployment.",
					"iconId":"composition.scaleout.png",
					"type":"ACTION",
					"id":"7d66f361-ce64-493a-be4f-fc042b6908f5",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.component.cafe.composition",
					"bindingId":"composition.resource.action.deployment.scaleout",
					"hasForm":true,
					"formScale":"BIG"
				 }
			  ],
			  "forms":{  
				 "catalogResourceInfoHidden":false,
				 "details":{  
					"type":"external",
					"formId":"composition.deployment.details"
				 }
			  },
			  "resourceData":{  
				 "entries":[  
	 
				 ]
			  },
			  "destroyDate":"2019-03-04T00:59:28.210Z"
		   },
		   {  
			  "@type":"CatalogResource",
			  "id":"337785f3-c946-4fd7-89d6-8b34a243c345",
			  "iconId":"Infrastructure.CatalogItem.Machine.Virtual.vSphere",
			  "resourceTypeRef":{  
				 "id":"Infrastructure.Virtual",
				 "label":"Virtual Machine"
			  },
			  "name":"Development0233",
			  "description":null,
			  "status":"ACTIVE",
			  "catalogItem":null,
			  "requestId":"6ec160e5-41c5-4b1d-8ddc-e89c426957c6",
			  "requestState":"SUCCESSFUL",
			  "providerBinding":{  
				 "bindingId":"c4546fda-dbb2-4839-848f-f8b7d64eb28a",
				 "providerRef":{  
					"id":"04379cf6-d805-49b3-b570-c27e49b7d08d",
					"label":"Infrastructure Service"
				 }
			  },
			  "owners":[  
				 {  
					"tenantName":"qe",
					"ref":"fritz@coke.sqa-horizon.local",
					"type":"USER",
					"value":"Fritz Arbeiter"
				 }
			  ],
			  "organization":{  
				 "tenantRef":"qe",
				 "tenantLabel":"QETenant",
				 "subtenantRef":"b2470b94-cbca-43db-be37-803cca7b0f1a",
				 "subtenantLabel":"Development"
			  },
			  "dateCreated":"2019-02-27T01:04:16.627Z",
			  "lastUpdated":"2019-02-27T01:11:58.959Z",
			  "hasLease":true,
			  "lease":{  
				 "start":"2019-02-27T00:59:28.210Z",
				 "end":"2019-03-04T00:59:28.210Z"
			  },
			  "leaseForDisplay":{  
				 "type":"timeSpan",
				 "unit":"DAYS",
				 "amount":5
			  },
			  "hasCosts":true,
			  "costs":null,
			  "costToDate":null,
			  "totalCost":null,
			  "expenseMonthToDate":{  
				 "amount":null,
				 "currencyCode":null,
				 "asOnDate":null
			  },
			  "parentResourceRef":{  
				 "id":"69ddca78-7ed7-45e2-9f05-a4a4c8803e5c",
				 "label":"Prativa_CentOs-66559687"
			  },
			  "hasChildren":false,
			  "operations":[  
				 {  
					"name":"Change Lease",
					"description":"Change the lease for a machine. Leave empty for indefinite.",
					"iconId":"machineChangeLease.png",
					"type":"ACTION",
					"id":"4f9c4707-b473-435b-94ec-ca453ab47f17",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.ChangeLease",
					"hasForm":true,
					"formScale":"SMALL"
				 },
				 {  
					"name":"Connect to Remote Console",
					"description":"Infrastructure connect using remote console",
					"iconId":"cafe_default_icon_genericResourceOperation",
					"type":"EXTENSION",
					"id":"613b34f4-f7c9-4171-87a3-79b6e6f7b82c",
					"extensionId":"csp.places.iaas.item.window.ConnectViaVmrc",
					"providerTypeId":null,
					"bindingId":null,
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Connect using RDP",
					"description":"Infrastructure connect using RDP",
					"iconId":"cafe_default_icon_genericResourceOperation",
					"type":"EXTENSION",
					"id":"9502bf90-c3f1-4288-b65d-333e91eda1b8",
					"extensionId":"csp.places.iaas.item.noform.ConnectViaRdp",
					"providerTypeId":null,
					"bindingId":null,
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Connect using VMRC",
					"description":"Infrastructure connect using VMRC",
					"iconId":"cafe_default_icon_genericResourceOperation",
					"type":"EXTENSION",
					"id":"6fd2487f-a437-4ead-bbf6-8e0d5ef1325d",
					"extensionId":"csp.places.iaas.item.nowindow.ConnectViaNativeVmrc",
					"providerTypeId":null,
					"bindingId":null,
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Create Snapshot",
					"description":"Create a snapshot for this machine.",
					"iconId":"virtualCreateSnapshot.png",
					"type":"ACTION",
					"id":"ff10d21e-abac-4ce9-8367-b30ad9ed5bb1",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Virtual.Action.CreateSnapshot",
					"hasForm":true,
					"formScale":"SMALL"
				 },
				 {  
					"name":"Destroy",
					"description":"Destroy a virtual machine.",
					"iconId":"virtualDestroy.png",
					"type":"ACTION",
					"id":"95e60c87-e4d6-4458-9bfe-af7955cadc06",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Virtual.Action.Destroy",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Expire",
					"description":"Expire a machine.",
					"iconId":"machineExpire.png",
					"type":"ACTION",
					"id":"731ee464-8b4c-4c8f-b46d-debd5a579a7d",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Expire",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Install Tools",
					"description":"Install tools on a machine.",
					"iconId":"machineInstallTools.png",
					"type":"ACTION",
					"id":"0202c42e-435b-48ed-9ecc-fdc4e3961488",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.InstallTools",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Power Cycle",
					"description":"Reset a machine.",
					"iconId":"machineReset.png",
					"type":"ACTION",
					"id":"80236704-3faa-48ac-a897-e1836bada268",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Reset",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Power Off",
					"description":"Power off a machine.",
					"iconId":"machinePowerOff.png",
					"type":"ACTION",
					"id":"8f664760-5d2d-4e97-8ae3-7fa515144f72",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.PowerOff",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Reboot",
					"description":"Reboot a machine.",
					"iconId":"machineReboot.png",
					"type":"ACTION",
					"id":"a66d10d0-52af-4799-a953-5c17bca5438a",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Reboot",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Reconfigure",
					"description":"Reconfigure a machine.",
					"iconId":"machineReconfigure.png",
					"type":"ACTION",
					"id":"1a22752b-31a9-462e-a38a-e42b60c08a78",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Reconfigure",
					"hasForm":true,
					"formScale":"BIG"
				 },
				 {  
					"name":"Reprovision",
					"description":"Reprovision a machine.",
					"iconId":"machineReprovision.png",
					"type":"ACTION",
					"id":"41aedd39-6deb-42e3-89ee-75f4ea352df6",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Reprovision",
					"hasForm":true,
					"formScale":"BIG"
				 },
				 {  
					"name":"Shutdown",
					"description":"Shutdown a machine.",
					"iconId":"machineShutdown.png",
					"type":"ACTION",
					"id":"d38400bb-926f-4d85-bea0-6fb828b42e47",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Shutdown",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Suspend",
					"description":"Suspend a machine.",
					"iconId":"machineSuspend.png",
					"type":"ACTION",
					"id":"f9b8814d-1757-4d01-a8f8-ca86ea5ea83c",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Suspend",
					"hasForm":false,
					"formScale":null
				 },
				 {  
					"name":"Unregister",
					"description":"Unregister a machine.",
					"iconId":"machineUnregister.png",
					"type":"ACTION",
					"id":"28ef23c1-dc33-4f95-87fb-c25fa11b304a",
					"extensionId":null,
					"providerTypeId":"com.vmware.csp.iaas.blueprint.service",
					"bindingId":"Infrastructure.Machine.Action.Unregister",
					"hasForm":false,
					"formScale":null
				 }
			  ],
			  "forms":{  
				 "catalogResourceInfoHidden":true,
				 "details":{  
					"type":"extension",
					"extensionId":"csp.places.iaas.item.details",
					"extensionPointId":null
				 }
			  },
			  "resourceData":{  
				 "entries":[  
					{  
					   "key":"DISK_VOLUMES",
					   "value":{  
						  "type":"multiple",
						  "elementTypeId":"COMPLEX",
						  "items":[  
							 {  
								"type":"complex",
								"componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
								"componentId":null,
								"classId":"dynamicops.api.model.DiskInputModel",
								"typeFilter":null,
								"values":{  
								   "entries":[  
									  {  
										 "key":"DISK_INPUT_ID",
										 "value":{  
											"type":"string",
											"value":"DISK_INPUT_ID1"
										 }
									  },
									  {  
										 "key":"DISK_CAPACITY",
										 "value":{  
											"type":"integer",
											"value":8
										 }
									  },
									  {  
										 "key":"DISK_LABEL",
										 "value":{  
											"type":"string",
											"value":"Hard disk 1"
										 }
									  }
								   ]
								}
							 }
						  ]
					   }
					},
					{  
					   "key":"MachineMemory",
					   "value":{  
						  "type":"integer",
						  "value":1024
					   }
					},
					{  
					   "key":"MachineGuestOperatingSystem",
					   "value":null
					},
					{  
					   "key":"MachineBlueprintName",
					   "value":{  
						  "type":"string",
						  "value":"Prativa_CentOs"
					   }
					},
					{  
					   "key":"Suspend",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"MachineCPU",
					   "value":{  
						  "type":"integer",
						  "value":2
					   }
					},
					{  
					   "key":"MachineInterfaceType",
					   "value":{  
						  "type":"string",
						  "value":"vSphere"
					   }
					},
					{  
					   "key":"MachineExpirationDate",
					   "value":{  
						  "type":"dateTime",
						  "value":"2019-03-04T00:59:31.527Z"
					   }
					},
					{  
					   "key":"PowerOff",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"ConnectViaNativeVmrc",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"IS_COMPONENT_MACHINE",
					   "value":{  
						  "type":"boolean",
						  "value":false
					   }
					},
					{  
					   "key":"ChangeLease",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"endpointExternalReferenceId",
					   "value":{  
						  "type":"string",
						  "value":"827cddd6-9fd7-4477-bd2f-89b6b6d04337"
					   }
					},
					{  
					   "key":"VirtualMachine.Admin.UUID",
					   "value":{  
						  "type":"string",
						  "value":"503626c3-612a-24b9-d978-4a211d0358b1"
					   }
					},
					{  
					   "key":"MachineInterfaceDisplayName",
					   "value":{  
						  "type":"string",
						  "value":"vSphere (vCenter)"
					   }
					},
					{  
					   "key":"Destroy",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"MachineReservationName",
					   "value":{  
						  "type":"string",
						  "value":"reservation-tf"
					   }
					},
					{  
					   "key":"NETWORK_LIST",
					   "value":{  
						  "type":"multiple",
						  "elementTypeId":"COMPLEX",
						  "items":[  
							 {  
								"type":"complex",
								"componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
								"componentId":null,
								"classId":"dynamicops.api.model.NetworkViewModel",
								"typeFilter":null,
								"values":{  
								   "entries":[  
									  {  
										 "key":"NETWORK_NAME",
										 "value":{  
											"type":"string",
											"value":"dvPortGroup-wdc-sdm-vm-1521"
										 }
									  },
									  {  
										 "key":"NETWORK_MAC_ADDRESS",
										 "value":{  
											"type":"string",
											"value":"00:50:56:b6:ff:38"
										 }
									  }
								   ]
								}
							 }
						  ]
					   }
					},
					{  
					   "key":"Reset",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"Component",
					   "value":{  
						  "type":"string",
						  "value":"machine2.vsphere"
					   }
					},
					{  
					   "key":"ConnectViaVmrc",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"InstallTools",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"SNAPSHOT_LIST",
					   "value":{  
						  "type":"multiple",
						  "elementTypeId":"COMPLEX",
						  "items":[  
	 
						  ]
					   }
					},
					{  
					   "key":"MachineStatus",
					   "value":{  
						  "type":"string",
						  "value":"On"
					   }
					},
					{  
					   "key":"MachineType",
					   "value":{  
						  "type":"string",
						  "value":"Virtual"
					   }
					},
					{  
					   "key":"MachineStorage",
					   "value":{  
						  "type":"integer",
						  "value":8
					   }
					},
					{  
					   "key":"EXTERNAL_REFERENCE_ID",
					   "value":{  
						  "type":"string",
						  "value":"vm-12090"
					   }
					},
					{  
					   "key":"ip_address",
					   "value":{  
						  "type":"string",
						  "value":"10.145.155.180"
					   }
					},
					{  
					   "key":"MachineGroupName",
					   "value":{  
						  "type":"string",
						  "value":"Development"
					   }
					},
					{  
					   "key":"Relocate",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"Reboot",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"ChangeOwner",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"Expire",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"machineId",
					   "value":{  
						  "type":"string",
						  "value":"c4546fda-dbb2-4839-848f-f8b7d64eb28a"
					   }
					},
					{  
					   "key":"Shutdown",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"MachineName",
					   "value":{  
						  "type":"string",
						  "value":"Development0233"
					   }
					},
					{  
					   "key":"MachineDestructionDate",
					   "value":{  
						  "type":"dateTime",
						  "value":"2019-03-04T00:59:31.527Z"
					   }
					},
					{  
					   "key":"Unregister",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"Reconfigure",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"ConnectViaRdp",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"Reprovision",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"CreateSnapshot",
					   "value":{  
						  "type":"boolean",
						  "value":true
					   }
					},
					{  
					   "key":"MachineDailyCost",
					   "value":{  
						  "type":"decimal",
						  "value":0.0
					   }
					}
				 ]
			  },
			  "destroyDate":"2019-03-04T00:59:28.210Z"
		   }
		],
		"metadata":{  
		   "size":20,
		   "totalElements":2,
		   "totalPages":1,
		   "number":1,
		   "offset":0
		}
	 }`

	deleteActionTemplateResponse = `{  
		"type":"com.vmware.vcac.catalog.domain.request.CatalogResourceRequest",
		"resourceId":"0786a919-3545-408d-9091-cc8fe24e7790",
		"actionId":"1a22752b-31a9-462e-a38a-e42b60c08a78",
		"description":null,
		"reasons":null,
		"data":{  
		   "ForceDestroy":false,
		   "provider-DeleteVolumes":false
		}
	 }`

	reconfigureActionTemplateResponse = `{  
		"type":"com.vmware.vcac.catalog.domain.request.CatalogResourceRequest",
		"resourceId":"0786a919-3545-408d-9091-cc8fe24e7790",
		"actionId":"1a22752b-31a9-462e-a38a-e42b60c08a78",
		"description":null,
		"reasons":null,
		"data":{  
		   "allowForceShutdown":"false",
		   "cpu":1,
		   "customProperties":[  
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"_number_of_instances",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"1"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"Cafe.Shim.VirtualMachine.TotalStorageSize",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"8"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"location.loc",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"Palo Alto 1"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"providerBindingId",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"Prativa_CentOs"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"providerId",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"701feaf9-c31c-4bf1-86b6-8638002e32eb"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"subtenantId",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"b2470b94-cbca-43db-be37-803cca7b0f1a"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"trace_id",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"R34g5F04"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Admin.AgentID",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"6b473642-1fa1-e1b2-ddda-01acafaaf202"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Admin.TotalDiskUsage",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"8192"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Admin.UUID",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"503620d8-96cd-0866-f652-e605d199c6e9"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Cafe.Blueprint.Component.Cluster.Index",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"0"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Cafe.Blueprint.Component.Id",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"machine2.vsphere"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Cafe.Blueprint.Component.TypeId",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"Infrastructure.CatalogItem.Machine.Virtual.vSphere"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Cafe.Blueprint.Id",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"Prativa_CentOs"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Cafe.Blueprint.Name",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"Prativa_CentOs"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.CPU.Count",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"1"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Memory.Size",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"1024"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"VirtualMachine.Storage.Name",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"wdc-eso-ins-a-VMs-1"
				 }
			  },
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.CustomProperty",
				 "typeFilter":null,
				 "data":{  
					"id":"Vrm.ProxyAgent.Uri",
					"is_encrypted":false,
					"is_hidden":false,
					"prompt_user":false,
					"value":"https://host.eng.vmware.com/"
				 }
			  }
		   ],
		   "description":null,
		   "disks":[  
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.Compute.Machine.MachineDisk",
				 "typeFilter":null,
				 "data":{  
					"customProperties":[  
					   {  
						  "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
						  "componentId":null,
						  "classId":"Infrastructure.CustomProperty",
						  "typeFilter":null,
						  "data":{  
							 "id":"IsClone",
							 "is_encrypted":false,
							 "is_hidden":false,
							 "prompt_user":false,
							 "value":"true"
						  }
					   },
					   {  
						  "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
						  "componentId":null,
						  "classId":"Infrastructure.CustomProperty",
						  "typeFilter":null,
						  "data":{  
							 "id":"Name",
							 "is_encrypted":false,
							 "is_hidden":false,
							 "prompt_user":false,
							 "value":"Hard disk 1"
						  }
					   }
					],
					"driveLetter":null,
					"externalId":"6000C29d-a1aa-db33-800f-6c1a1c725057",
					"label":"Hard disk 1",
					"reservationPolicy":null,
					"reservationPolicyMode":null,
					"size":8,
					"storagePath":"wdc-eso-ins-a-VMs-1"
				 }
			  }
		   ],
		   "executionSelector":"1",
		   "memory":1024,
		   "name":"Development0234",
		   "nics":[  
			  {  
				 "componentTypeId":"com.vmware.csp.component.iaas.proxy.provider",
				 "componentId":null,
				 "classId":"Infrastructure.Compute.Machine.Nic",
				 "typeFilter":null,
				 "data":{  
					"macAddress":"00:50:56:b6:8a:02",
					"name":"dvPortGroup-wdc-sdm-vm-1521"
				 }
			  }
		   ],
		   "powerActionSelector":"0",
		   "requestor":"APIUser",
		   "storage":8
		}
	 }`

	invalidResourceErrorResponse = `{  
		"errors":[  
		   {  
			  "code":10101,
			  "source":null,
			  "message":"Invalid argument.",
			  "systemMessage":"The provided resource was null.",
			  "moreInfoUrl":null
		   }
		]
	 }`

	systemExceptionResponse = `{  
		"errors":[  
		   {  
			  "code":50505,
			  "source":null,
			  "message":"System exception.",
			  "systemMessage":null,
			  "moreInfoUrl":null
		   }
		]
	 }`
)
